FROM registry.access.redhat.com/ubi8/ubi-init 


# ssh, systemd, passwordless sudo container for ansible target use etc

LABEL maintainer="Tok - Tony Kay"

ENV ssh_port=22

ARG RHN_PASSWORD
ARG RHN_USERNAME
ARG foo=$foo

#ENV RHN_PASSWORD=$RHN_PASSWORD
#ENV RHN_USERNAME=${RHN_USERNAME:-tok}

#RUN echo ssh is $RHN_USERNAME

RUN subscription-manager register --auto-attach --username ${RHN_USERNAME:-foo} --password ${RHN_PASSWORD} 

# install ssh server and configure 
# setup the vagrant user, vagrant insecure key, passwordless sudo

#RUN export RHN_USERNAME=${RHN_USERNAME} && \
#    subscription-manager register --auto-attach --username ${RHN_USERNAME:-foo} --password ${RHN_PASSWORD} 

#RUN subscription-manager register --auto-attach --username ${RHN_USERNAME} --password Okaya8tok!  
#RUN export RHN_USERNAME=${RHN_USERNAME} && \
#    export RHN_PASSWORD=${RHN_PASSWORD} && \
#    bash -ic "subscription-manager register --auto-attach --username $RHN_USERNAME --password ${RHN_PASSWORD}"

#RUN export RHN_USERNAME=${RHN_USERNAME} && \
#    export sub_command="subscription-manager register --auto-attach --username ${RHN_USERNAME} --password ${RHN_PASSWORD}" && \
#  $sub_command 

ENV user=vagrant
RUN    yum install -y openssh-server sudo && \
# setup sshd, install sudo
    echo "RSAAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key && \
    systemctl enable sshd.service && \
# setup user, defaults to vagrant and ssh keys, use COPY to inject your own
    useradd ${user:-vagrant} && \ 
    mkdir -p /home/${user:-vagrant}/.ssh && \
    curl -LSs https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub > /home/vagrant/.ssh/authorized_keys && \
    chmod 600 /home/${user:-vagrant}/.ssh/authorized_keys && chmod 700 /home/${user:-vagrant}/.ssh && \
    chown -R ${user:-vagrant}:${user:-vagrant} /home/${user:-vagrant}/.ssh && \
# setup passwordless sudo for user
    echo "${user:-vagrant} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
# clean up
    yum clean all && \
    rm -rf /var/cache/yum

# COPY centos-sshd_config centos-sshd_config

# expose ssh port, defaults to 22

EXPOSE ${ssh_port:-22}
EXPOSE 8888

CMD ["/sbin/init"]
