FROM registry.access.redhat.com/ubi8/ubi-init 

# ssh, systemd, passwordless sudo container for ansible target use etc
#
# NOTE! SECURITY implications, container must be run in privilged mode 
#
# docker run -d -p 22:22 --rm --privileged --name rhel8-ssh rhel8-ssh

LABEL maintainer="Tok - Tony Kay tony.g.kay@gmail.com"

# Red Hat Subscription creds need to be supplied via --build-args
#
# docker build -t rhel8-ssh -f Dockerfile-rhel8 --build-arg RHN_USERNAME=${RHN_USERNAME} --build-arg
# RHN_PASSWORD=${RHN_PASSWORD} .

ARG RHN_PASSWORD
ARG RHN_USERNAME

ENV SSH_PORT=22
ENV SSH_USER=vagrant
ENV SSH_KEY_URL=https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub

# 1) Register to Red Hat Network (a yum server or EPEL would be an alternative
# 2) Install, configure, and enable sshd
# 3) Add a user and ssh public key - NB consider NOT using vagrant or at least 
#    use a secure key
# 4) OPTIONAL, enable passwordless sudo   

RUN subscription-manager register --auto-attach --username ${RHN_USERNAME} --password ${RHN_PASSWORD} && \
    yum install -y openssh-server sudo && \
    echo "RSAAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key && \
    systemctl enable sshd.service && \
    useradd ${SSH_USER} && \ 
    mkdir -p /home/${SSH_USER}/.ssh && \
    curl -LSs ${SSH_KEY_URL} > /home/${SSH_USER}/.ssh/authorized_keys && \
    # curl -LSs https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub > /home/${SSH_USER}/.ssh/authorized_keys && \
    chmod 600 /home/${SSH_USER}/.ssh/authorized_keys && chmod 700 /home/${SSH_USER}/.ssh && \
    chown -R ${SSH_USER}:${SSH_USER:-vagrant} /home/${SSH_USER}/.ssh && \
    echo "${SSH_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    yum clean all && \
    rm -rf /var/cache/yum

# expose ssh port, defaults to 22

EXPOSE ${SSH_PORT:-22}

CMD ["/sbin/init"]
