FROM centos/systemd

MAINTAINER tok
# https://gist.github.com/lenchevsky/7eba11bd491e70105de3600ec9ec1292

# Install base packages and enable sshd

RUN yum -y install openssh-server sudo nano epel-release openssl certmonger \ 
  systemctl enable sshd.service

# Enable root and vagrant accounts

RUN echo 'root:vagrant' | chpasswd
RUN adduser vagrant && \
	echo 'vagrant:vagrant' | chpasswd && \
	usermod -aG wheel vagrant
	
# Configure SSHD

RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd
# http://stackoverflow.com/questions/2419412/ssh-connection-stop-at-debug1-ssh2-msg-kexinit-sent
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
# Bad security, add a user and sudo instead!
#RUN sed -ri 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
# http://stackoverflow.com/questions/18173889/cannot-access-centos-sshd-on-docker
#RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
#RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

# Deploy ssh keys

COPY vagrant.pub /tmp/vagrant.pub

#RUN mkdir /root/.ssh/ && \
#	cat /tmp/vagrant.pub >> ~/.ssh/authorized_keys && \
#	chmod 700 ~/.ssh && \
#	chmod 600 ~/.ssh/authorized_keys

RUN mkdir /home/vagrant/.ssh/ && \
	cat /tmp/vagrant.pub >> /home/vagrant/.ssh/authorized_keys && \
	chmod 700 /home/vagrant/.ssh && \
	chmod 600 /home/vagrant/.ssh/authorized_keys && \
	chown -R vagrant:vagrant /home/vagrant/.ssh/

# Configure vagrant
RUN bash -c 'echo "vagrant ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'

EXPOSE 22
EXPOSE 2000
EXPOSE 8080

WORKDIR /
RUN systemctl set-default multi-user.target
ENV init /lib/systemd/systemd
# VOLUME [ "/sys/fs/cgroup" ]

#ENTRYPOINT ["/lib/systemd/systemd"]
CMD ["/usr/sbin/init"]
